spring:
  application:
    name: CONFIGSERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/trimoyee-g/microservice-config
          clone-on-start: true

server:
  port: 8085